# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2
project_name: polyenv

before:
  hooks:
    - go mod tidy
    - go mod download
    - go mod vendor

builds:
  - id: polyenv
    binary: polyenv
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
      - GOFLAGS={{ if isEnvSet "CI" }}-buildvcs=false{{ end }}
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarm: "7"
    # flags are passed to the 'go build' command.
    # buildvcs removes any git metadata from the binary,
    # making sure its not required when running outide of the git repo.
    # flags:
    #   - -buildvcs=false
    # ldflags are passed to the linker.
    ldflags:
      - -s -w
      - >-
        {{- if not (isEnvSet "CI") }}
        -X "github.com/withholm/polyenv/cmd.version=dev" -X "github.com/withholm/polyenv/cmd.commit=local" -X "github.com/withholm/polyenv/cmd.date=$(date +'%Y-%m-%d')"
        {{- else }}
        -X "github.com/withholm/polyenv/cmd.version={{.Version}}" -X "github.com/withholm/polyenv/cmd.commit={{.Commit}}" -X "github.com/withholm/polyenv/cmd.date={{.Date}}"
        {{- end }}
archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        formats: ["zip"]
    files:
      - LICENSE
      - README.md
checksum:
  name_template: "checksums.txt"
  algorithm: sha256
snapshot:
  version_template: "nightly-{{ .ShortCommit }}"
release:
  github:
      owner: WithHolm
      name: polyenv
  prerelease: auto
  draft: true
  replace_existing_draft: true
  replace_existing_artifacts: true
  
  mode: replace
  
source:
  enabled: true
  format: tar.gz
# changelog:
#   sort: asc
#   filters:
#     exclude:
#       - '^docs:'
#       - '^test:'
#       - '^chore:'
# scoops:
#   - name: polyenv
#     url_template: "https://github.com/withholm/polyenv/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
#     license: MIT
#     commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
#     commit_author:
#       name: goreleaserbot
