name: Shared - Collect all changelogs

on:
  workflow_call:
    inputs:
      path:
        required: false
        type: string
        default: /changelog/current
    outputs:
      data:
        value: ${{ jobs.collect.outputs.changelog }}

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Collect all changelogs in /changelog/current
        id: collect
        run: |
          CHANGELOG_DETAILS=""
          ChangeLogPath="changelog/current"
          for file in ${{ inputs.path }}/*.md; do
            echo "Processing file: $file"
            PrNumber=$(basename "$file" .md)
            CHANGELOG_DETAILS="${CHANGELOG_DETAILS}### [$PrNumber](https://github.com/WithHolm/polyenv/pull/$PrNumber)\n\n"
            CHANGELOG_DETAILS="${CHANGELOG_DETAILS}$(cat "$file")\n\n"
          done

          echo 'changelog<<EOF' >> $GITHUB_OUTPUT
          echo -e "$CHANGELOG_DETAILS" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
