name: Shared - Generate changelog file

on:
  workflow_call:
    inputs:
      changelog_text:
        required: true
        type: string
      repo:
        required: true
        type: string
      pr_number:
        required: true
        type: string
      commit_ref:
        required: true
        type: string
      dependabot_pr:
        required: false
        type: boolean
        default: false
      check_changelog_exist:
        required: false
        type: boolean
        default: false
    outputs:
      file_exists:
        value: ${{ jobs.check_file.outputs.file_exists }}

jobs:
  check_file:
    runs-on: ubuntu-latest
    outputs:
      file_exists: ${{ steps.check_file.outputs.file_exists }}
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v5
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.commit_ref }}
      - name: generate file name
        id: generate_file_name
        run: |
          CHANGELOG_PATH=""
          # Correctly check the boolean input
          if [[ "${{ inputs.dependabot_pr }}" == "true" ]]; then
            # Note: No spaces around the '=' for variable assignment
            CHANGELOG_PATH="changelog/current/bump/${{ inputs.pr_number }}.md"
          else
            CHANGELOG_PATH="changelog/current/${{ inputs.pr_number }}.md"
          fi

          # Set the path as an output for later steps
          echo "file_exists=$CHANGELOG_PATH" >> $GITHUB_OUTPUT
      - name: Check if bump file exists
        id: check_file
        run: |
          # Check if the changelog fragment file exists
          if [ -f "${{ steps.generate_file_name.outputs.changePath }}" ]; then
            echo "file_exists=true" >> $GITHUB_OUTPUT
          else
            echo "file_exists=false" >> $GITHUB_OUTPUT
          fi
  write-and-commit:
    runs-on: ubuntu-latest
    needs: check_file
    if: needs.check_file.outputs.file_exists == 'false' && !inputs.check_changelog_exist
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v5
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.commit_ref }}
      - name: Create changelog
        run: |
          DIR_PATH=$(dirname "${{ needs.check_file.outputs.file_exists }}")
          mkdir -p "$DIR_PATH"
          
          # Create the file
          echo "${{ inputs.changelog_text }}" > "${{ needs.check_file.outputs.file_exists }}"
      - name: Commit and push changelog fragment
        id: commit-changelog
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add "${{ needs.check_file.outputs.file_exists}}"
          # Check if there are any changes to commit before committing
          if ! git diff --staged --quiet; then
            git commit -m "docs(changelog): create/update fragment for PR #${{ inputs.pr_number }}"
            git push
          else
            echo "No changes to the changelog fragment file."
          fi