name: Shared - Test

on:
  workflow_call:
    inputs:
      full_test:
        type: boolean
        required: false
        default: false
      path:
        type: string
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: check
        if: inputs.path == '' && !inputs.full_test
        run: |
          echo "something is wrong"
          exit 1
      - uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true
      - name: install tools
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          go install honnef.co/go/tools/cmd/staticcheck@latest
      - name: concat path
        id: concat-path
        if: inputs.path != ''
        run: |
          if [["${{inputs.full_test}}" == "true"]]; then
            echo "path=./cmd/... ./internal/..." >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "path=./${{ inputs.path }}" >> $GITHUB_OUTPUT
      - name: Run staticcheck
        if: inputs.full_test
        run: |
          staticcheck "${{ steps.concat-path.outputs.path }}"
      - name: Run tests
        if: inputs.path != '' && !inputs.full_test
        run: |
          go test -v -race "${{ steps.concat-path.outputs.path }}"
      - name: Run govulncheck
        if: inputs.path != ''
        run: |
          govulncheck "${{ steps.concat-path.outputs.path }}"
