name: Changelog - Create Fragment on PR Open

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches: [dev]

env:
  header: "## Changes"

jobs:
  check_if_changelog_exists:
    if: ${{github.actor != 'dependabot[bot]'}}
    runs-on: ubuntu-latest
    outputs:
      changelog_exists: ${{ steps.check_changelog.outputs.changelog_exists }}
    steps:
      - name: Check if changelog fragment exists
        id: check_changelog
        uses: ./.github/workflows/shared/check_changelog-file.yaml
        with:
          pr-number: ${{ github.event.pull_request.number }}
          repo: ${{ github.event.pull_request.head.repo.full_name }}
          commit-ref: ${{ github.event.pull_request.head.ref }}
          check_changelog_exist: true
          changelog-text: ""
  create-changelog-fragment:
    runs-on: ubuntu-latest
    needs: check_if_changelog_exists
    if: needs.check_if_changelog_exists.outputs.changelog_exists == 'false'
    permissions:
      contents: write
    steps:
      - name: Extract changelog from PR body
        id: extract-changelog
        run: |
          # Use awk to extract content between "${{ github.event.pull_request.body}}" and the next "##" heading. remove multiline comments
          content=$(echo "${{ github.event.pull_request.body}}" | awk '/^${{env.header}}/{flag=1; next} /^##/{flag=0} flag' | perl -0777 -pe 's/<!--.*?-->//sg' | xargs)

          if [ -n "$content" ]; then
            echo "Changelog content found:"
            echo "$content"
            
            echo "content=$content" >> $GITHUB_OUTPUT
            echo "content_found=true" >> $GITHUB_OUTPUT
          else
            echo "No changelog content found under ## Description."
            echo "content_found=false" >> $GITHUB_OUTPUT
          fi
      - name: push changelog fragment
        id: push_changelog
        if: steps.extract-changelog.outputs.content_found == 'true'
        uses: ./.github/workflows/shared/generate-changelog-file.yaml
        with:
          changelog_text: ${{ steps.extract-changelog.outputs.content }}
          repo: ${{ github.event.pull_request.head.repo.full_name }}
          pr_number: ${{ github.event.pull_request.number }}
          commit_ref: ${{ github.event.pull_request.head.ref }}
