name: Check Licence

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**/*.go'


jobs:
  check-licence:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true
      - name: Check licence
        uses: withholm/check-licence-action@v1
        with:
          path: "**/*.go"
          fail-on-non-approved: true