name: "Apply labels"

on:
  pull_request:
    types: [opened, synchronize,reopened]

permissions:
    contents: read
    pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yml