on:
  push:
    branches: [ "main" ]
    tags:
      - "v*.*.*" # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  goreleaser_version: ~> v2
  goreleaser_dist: goreleaser
#   Variables: .github/variables/common.env

name: Build and Release

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true
      
      - name: ref
        run: |
          echo "ref: ${{ github.ref }}"
          echo "ref_name: ${{ github.ref_name }}"
          echo "ref_type: ${{ github.ref_type }}"
          echo "sha: ${{ github.sha }}"
          echo "event_name: ${{ github.event_name }}"
          echo "event.ref: ${{ github.event.ref }}"
          echo "event.inputs.ref: ${{ github.event.inputs.ref }}"
          echo "github.ref: ${{ github.ref }}"
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "github.ref_type: ${{ github.ref_type }}"
          echo "github.sha: ${{ github.sha }}"
          echo "github.event_name: ${{ github.event_name }}"
          echo "github.event.ref: ${{ github.event.ref }}"
          echo "github.event.inputs.ref: ${{ github.event.inputs.ref }}"
      # - name: Go mod tidy
      #   run: |
      #       go mod tidy -v

      # - name: Go mod vendor
      #   run: |
      #     go mod vendor -v

      # - name: git add any changes with tag
      #   run: |
      #     git config --global user.email "github-actions[bot]@users.noreply.github.com"
      #     git config --global user.name "github-actions[bot]"
      #     git add .
      #     git tag ${{ github.ref_name }}
      #     git commit -m "go mod tidy for tag ${{ github.ref_name }}"

      # - name: Install GoReleaser
      #   uses: goreleaser/goreleaser-action@v6
      #   with:
      #     version: ${{ env.goreleaser_version }}
      #     distribution: ${{ env.goreleaser_dist }}
      #     install-only: true

      # - name: Build and release
      #   id: goreleaser
      #   uses: goreleaser/goreleaser-action@v6
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     version: ${{ env.goreleaser_version }}
      #     distribution: ${{ env.goreleaser_dist }}
      #     args: release --clean --verbose --draft



