on:
  push:
    tags:
      - "v*.*.*" # This workflow will now ONLY run when a tag matching v*.*.* is pushed

env:
  goreleaser_version: ~> v2
  goreleaser_dist: goreleaser
#   Variables: .github/variables/common.env

name: Build and Release

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      # - name: Build and release
      #   id: goreleaser
      #   uses: goreleaser/goreleaser-action@v6
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     version: ${{ env.goreleaser_version }}
      #     distribution: ${{ env.goreleaser_dist }}
      #     args: release --clean --verbose --draft



