name: Test TUI
on:
  workflow_dispatch:
    inputs:
      command:
        description: 'command to run'
        required: true
        type: string

runs-on: ubuntu-latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: setup temp
        run: |
          "[options]
            hyphens_to_underscores = true
            uppercase_locally = true
            use_dot_secret_file_for_secrets = true" >> .polyenv.toml

          echo "some_key=1234567890abcdef1234567890abcdef" >> .env
          echo "some_key2=1234567890abcdef1234567890abcdef" >> .env.secret

      - name: Run command
        run: go run main.go ${{ github.event.inputs.command }}